version: "3"

services:
  api:
    build:
        dockerfile: Api.Dockerfile
        context: .
    volumes:
      - ./api:/code
    networks:
      - traefik_webgateway
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`api.mysuperapp.localhost`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_webgateway"

  frontend:
    build:
      dockerfile: Frontend.Dockerfile
      context: .
    networks:
      - traefik_webgateway
    depends_on:
      - api
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html/
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webappfrontend.rule=Host(`mysuperapp.localhost`)"
      - "traefik.http.routers.webappfrontend.entrypoints=web"
      - "traefik.http.services.webappfrontend.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_webgateway"

networks:
  traefik_webgateway:
    external: true